#!/usr/bin/env bash
# Concatenates all migrations into supabase/setup_new_project.sql: one file to
# paste into the SQL Editor of a brand-new Supabase project. Re-run after
# adding a migration.
set -euo pipefail
cd "$(dirname "$0")"
OUT=setup_new_project.sql
{
  echo "-- GENERATED by supabase/build-setup.sh - do not edit by hand."
  echo "-- Full database setup for a NEW, EMPTY Supabase project."
  echo "-- Paste everything into SQL Editor -> New query -> Run."
  echo "-- Runs in one transaction: either everything is created or nothing is."
  echo
  echo "BEGIN;"
  for f in migrations/*.sql; do
    echo
    echo "-- ═══ $f ═══"
    cat "$f"
    echo
  done
  echo
  echo "COMMIT;"
} > "$OUT"
echo "wrote supabase/$OUT"
