-- GENERATED by supabase/build-setup.sh - do not edit by hand.
-- Full database setup for a NEW, EMPTY Supabase project.
-- Paste everything into SQL Editor -> New query -> Run.
-- Runs in one transaction: either everything is created or nothing is.

BEGIN;

-- ═══ migrations/20260125171054_6886b496-7266-4464-b25a-dc96c884970c.sql ═══
-- Tabela za termine zakazivanja
CREATE TABLE public.appointments (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_email TEXT,
  appointment_date DATE NOT NULL,
  appointment_time TIME NOT NULL,
  service_type TEXT NOT NULL,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'cancelled')),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

-- Policy: Anyone can create appointments (public booking)
CREATE POLICY "Anyone can create appointments" 
ON public.appointments 
FOR INSERT 
WITH CHECK (true);

-- Policy: Anyone can view appointments for availability check (only date/time needed)
CREATE POLICY "Public can check availability" 
ON public.appointments 
FOR SELECT 
USING (true);

-- Create index for faster date lookups
CREATE INDEX idx_appointments_date ON public.appointments(appointment_date);

-- Create function to update timestamps
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

-- Create trigger for automatic timestamp updates
CREATE TRIGGER update_appointments_updated_at
BEFORE UPDATE ON public.appointments
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- ═══ migrations/20260211100000_fix_rls_and_unique_constraint.sql ═══
-- ============================================
-- 1. UNIQUE constraint: sprečava dupla zakazivanja na isti datum/vreme
--    Partial unique index - važi samo za termine koji NISU otkazani
-- ============================================
CREATE UNIQUE INDEX idx_unique_appointment_slot
ON public.appointments (appointment_date, appointment_time)
WHERE status != 'cancelled';

-- ============================================
-- 2. Restriktivniji RLS: javni korisnici vide SAMO datum i vreme
--    (ne lične podatke klijenata)
-- ============================================

-- Ukloni stari previše otvoreni SELECT policy
DROP POLICY IF EXISTS "Public can check availability" ON public.appointments;

-- Novi policy: javni korisnici mogu čitati samo za proveru dostupnosti
-- Ali RLS ne može ograničiti kolone, pa koristimo Supabase RPC funkciju
-- Za sada ostavljamo SELECT ali ćemo koristiti RPC za availability check

-- Kreiramo sigurnu RPC funkciju koja vraća SAMO zauzete slotove (datum + vreme)
CREATE OR REPLACE FUNCTION public.get_booked_slots(check_date DATE)
RETURNS TABLE (appointment_time TIME) AS $$
BEGIN
  RETURN QUERY
  SELECT a.appointment_time
  FROM public.appointments a
  WHERE a.appointment_date = check_date
    AND a.status != 'cancelled';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Restriktivniji SELECT policy: blokiramo javni pristup ličnim podacima
-- Samo autentifikovani admin korisnici mogu videti sve podatke
DROP POLICY IF EXISTS "Public can check availability" ON public.appointments;

CREATE POLICY "Authenticated users can view all appointments"
ON public.appointments
FOR SELECT
USING (auth.role() = 'authenticated');

-- Policy za UPDATE: samo autentifikovani korisnici (admin)
CREATE POLICY "Authenticated users can update appointments"
ON public.appointments
FOR UPDATE
USING (auth.role() = 'authenticated');

-- Policy za DELETE: samo autentifikovani korisnici (admin)
CREATE POLICY "Authenticated users can delete appointments"
ON public.appointments
FOR DELETE
USING (auth.role() = 'authenticated');


-- ═══ migrations/20260216_hybrid_booking.sql ═══
-- Update appointments table
ALTER TABLE appointments 
  ADD COLUMN source text NOT NULL DEFAULT 'online' CHECK (source IN ('online', 'walkin')),
  ADD COLUMN end_time timestamptz,
  -- Convert appointment_date and appointment_time to timestamptz
  ADD COLUMN start_time timestamptz;

-- Migrate existing data
UPDATE appointments 
SET start_time = (appointment_date || ' ' || appointment_time)::timestamptz,
    end_time = (appointment_date || ' ' || appointment_time)::timestamptz + interval '1 hour'
WHERE start_time IS NULL;

-- Create indexes
CREATE INDEX idx_appointments_start_time ON appointments(start_time);
CREATE INDEX idx_appointments_status ON appointments(status);

-- Create salon settings
CREATE TABLE salon_settings (
  id integer PRIMARY KEY CHECK (id = 1),
  total_capacity integer NOT NULL DEFAULT 7,
  online_ratio numeric NOT NULL DEFAULT 0.6 CHECK (online_ratio > 0 AND online_ratio <= 1),
  max_online_per_slot integer NOT NULL DEFAULT 4,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Insert default settings
INSERT INTO salon_settings (id) VALUES (1);

-- Function to check slot availability
CREATE OR REPLACE FUNCTION check_slot_availability(
  check_start timestamptz,
  check_end timestamptz
) RETURNS json AS $$
DECLARE
  settings record;
  online_count integer;
  total_count integer;
  result json;
BEGIN
  -- Get salon settings
  SELECT * INTO settings FROM salon_settings WHERE id = 1;
  
  -- Count existing appointments that overlap with the time slot
  SELECT 
    COUNT(*) FILTER (WHERE source = 'online'),
    COUNT(*)
  INTO 
    online_count,
    total_count
  FROM appointments
  WHERE status = 'confirmed'
    AND NOT (end_time <= check_start OR start_time >= check_end);

  -- Determine slot state
  IF total_count >= settings.total_capacity THEN
    result := json_build_object(
      'state', 'FULL',
      'online_count', online_count,
      'total_count', total_count,
      'max_online', settings.max_online_per_slot,
      'total_capacity', settings.total_capacity
    );
  ELSIF online_count >= settings.max_online_per_slot THEN
    result := json_build_object(
      'state', 'ONLINE_FULL_WALKIN_AVAILABLE',
      'online_count', online_count,
      'total_count', total_count,
      'max_online', settings.max_online_per_slot,
      'total_capacity', settings.total_capacity
    );
  ELSE
    result := json_build_object(
      'state', 'ONLINE_AVAILABLE',
      'online_count', online_count,
      'total_count', total_count,
      'max_online', settings.max_online_per_slot,
      'total_capacity', settings.total_capacity
    );
  END IF;

  RETURN result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to create appointment with capacity check
CREATE OR REPLACE FUNCTION create_appointment(
  p_customer_name text,
  p_customer_phone text,
  p_customer_email text,
  p_start_time timestamptz,
  p_end_time timestamptz,
  p_service_type text,
  p_notes text DEFAULT NULL,
  p_source text DEFAULT 'online'
) RETURNS json AS $$
DECLARE
  slot_status json;
  settings record;
BEGIN
  -- Get salon settings
  SELECT * INTO settings FROM salon_settings WHERE id = 1;
  
  -- Check slot availability
  slot_status := check_slot_availability(p_start_time, p_end_time);
  
  -- Validate based on source
  IF p_source = 'online' AND (slot_status->>'state' != 'ONLINE_AVAILABLE') THEN
    RETURN json_build_object(
      'success', false,
      'error', 'Online booking not available for this slot',
      'status', slot_status
    );
  END IF;
  
  IF (slot_status->>'state')::text = 'FULL' THEN
    RETURN json_build_object(
      'success', false,
      'error', 'Slot is fully booked',
      'status', slot_status
    );
  END IF;

  -- Insert appointment
  INSERT INTO appointments (
    customer_name,
    customer_phone,
    customer_email,
    start_time,
    end_time,
    service_type,
    notes,
    source,
    status
  ) VALUES (
    p_customer_name,
    p_customer_phone,
    p_customer_email,
    p_start_time,
    p_end_time,
    p_service_type,
    p_notes,
    p_source,
    'confirmed'
  );

  RETURN json_build_object(
    'success', true,
    'status', check_slot_availability(p_start_time, p_end_time)
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- ═══ migrations/20260306_admin_features.sql ═══
-- Create table for managing holidays / blocked dates
CREATE TABLE salon_holidays (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  holiday_date DATE NOT NULL UNIQUE,
  reason TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE salon_holidays ENABLE ROW LEVEL SECURITY;

-- Policy: Only authenticated users (admins) can manage holidays
CREATE POLICY "Admins can manage holidays" 
ON salon_holidays 
FOR ALL 
USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');

-- Policy: Public can read holidays to check availability
CREATE POLICY "Public can view holidays" 
ON salon_holidays 
FOR SELECT 
USING (true);

-- Create trigger for automatic timestamp updates on holidays
CREATE TRIGGER update_salon_holidays_updated_at
BEFORE UPDATE ON salon_holidays
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Function to perfectly update an appointment
CREATE OR REPLACE FUNCTION update_appointment(
  p_appointment_id UUID,
  p_start_time TIMESTAMPTZ,
  p_end_time TIMESTAMPTZ,
  p_service_type TEXT,
  p_customer_name TEXT,
  p_customer_phone TEXT,
  p_notes TEXT,
  p_status TEXT
) RETURNS json AS $$
DECLARE
  slot_status json;
  settings record;
  current_appointment record;
BEGIN
  -- Get current appointment details BEFORE making any changes
  SELECT * INTO current_appointment FROM appointments WHERE id = p_appointment_id;
  
  IF NOT FOUND THEN
    RETURN json_build_object('success', false, 'error', 'Appointment not found');
  END IF;

  -- Only check availability again IF the time has changed AND it's not being cancelled
  IF (current_appointment.start_time != p_start_time OR current_appointment.end_time != p_end_time) AND p_status != 'cancelled' THEN
    
    -- Temporarily delete the current appointment so check_slot_availability doesn't count it against us
    DELETE FROM appointments WHERE id = p_appointment_id;

    -- Look at what the slots look like now
    slot_status := check_slot_availability(p_start_time, p_end_time);
    
    -- Does it fit?
    IF (slot_status->>'state')::text = 'FULL' OR (current_appointment.source = 'online' AND slot_status->>'state' != 'ONLINE_AVAILABLE') THEN
      -- Re-insert the old appointment details because we cannot move it here
      INSERT INTO appointments (id, customer_name, customer_phone, customer_email, start_time, end_time, service_type, notes, source, status, created_at, updated_at)
      VALUES (
        current_appointment.id, current_appointment.customer_name, current_appointment.customer_phone, 
        current_appointment.customer_email, current_appointment.start_time, current_appointment.end_time, 
        current_appointment.service_type, current_appointment.notes, current_appointment.source, 
        current_appointment.status, current_appointment.created_at, current_appointment.updated_at
      );
      
      RETURN json_build_object('success', false, 'error', 'Slot is fully booked or unavailable for this source.', 'status', slot_status);
    END IF;

    -- Space proved. Insert the appointment at its new spot.
    INSERT INTO appointments (id, customer_name, customer_phone, customer_email, start_time, end_time, service_type, notes, source, status, created_at, updated_at)
    VALUES (
      current_appointment.id, p_customer_name, p_customer_phone, current_appointment.customer_email, p_start_time, p_end_time, p_service_type, p_notes, current_appointment.source, p_status, current_appointment.created_at, now()
    );

  ELSE
    -- Time didn't change, just update the data attributes in-place
    UPDATE appointments 
    SET 
      customer_name = p_customer_name,
      customer_phone = p_customer_phone,
      service_type = p_service_type,
      notes = p_notes,
      status = p_status,
      updated_at = now()
    WHERE id = p_appointment_id;
  END IF;

  RETURN json_build_object('success', true, 'status', check_slot_availability(current_appointment.start_time, current_appointment.end_time));
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Overwriting check_slot_availability to INCLUDE holidays
CREATE OR REPLACE FUNCTION check_slot_availability(
  check_start timestamptz,
  check_end timestamptz
) RETURNS json AS $$
DECLARE
  settings record;
  online_count integer;
  total_count integer;
  result json;
  is_holiday boolean;
  req_date date;
BEGIN
  -- Get pure date from check_start
  req_date := DATE(check_start AT TIME ZONE 'UTC'); -- adjust timezone if absolutely necessary, but since DB stores UTC usually, basic DATE() is close enough.

  -- 1) Check if this date is a holiday
  SELECT EXISTS(SELECT 1 FROM salon_holidays WHERE holiday_date = req_date) INTO is_holiday;
  
  IF is_holiday THEN
    RETURN json_build_object(
      'state', 'FULL',
      'online_count', 0,
      'total_count', 0,
      'max_online', 0,
      'total_capacity', 0,
      'error', 'Salon is closed on this date (Holiday/Time-off)'
    );
  END IF;

  -- 2) Normal capacity logic down here
  SELECT * INTO settings FROM salon_settings WHERE id = 1;
  
  -- Count existing appointments that overlap with the time slot
  SELECT 
    COUNT(*) FILTER (WHERE source = 'online'),
    COUNT(*)
  INTO 
    online_count,
    total_count
  FROM appointments
  WHERE status = 'confirmed'
    AND NOT (end_time <= check_start OR start_time >= check_end);

  -- Determine slot state
  IF total_count >= settings.total_capacity THEN
    result := json_build_object(
      'state', 'FULL',
      'online_count', online_count,
      'total_count', total_count,
      'max_online', settings.max_online_per_slot,
      'total_capacity', settings.total_capacity
    );
  ELSIF online_count >= settings.max_online_per_slot THEN
    result := json_build_object(
      'state', 'ONLINE_FULL_WALKIN_AVAILABLE',
      'online_count', online_count,
      'total_count', total_count,
      'max_online', settings.max_online_per_slot,
      'total_capacity', settings.total_capacity
    );
  ELSE
    result := json_build_object(
      'state', 'ONLINE_AVAILABLE',
      'online_count', online_count,
      'total_count', total_count,
      'max_online', settings.max_online_per_slot,
      'total_capacity', settings.total_capacity
    );
  END IF;

  RETURN result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- ═══ migrations/20261001120000_security_hardening.sql ═══
-- ============================================================================
-- Security hardening + booking logic fixes
--
-- 1. Repairs schema drift from the first migration (legacy NOT NULL columns
--    and a unique index that contradict the hybrid capacity model).
-- 2. Introduces explicit admins (admin_users + is_admin()) instead of
--    "any authenticated user is an admin".
-- 3. Locks down RLS: no direct public INSERT into appointments, RLS on
--    salon_settings, admin-only writes everywhere.
-- 4. Rewrites the booking RPCs: input validation, server-side rules for
--    online bookings, per-phone limits, serialisation against overbooking,
--    timezone-correct holiday checks, and in-place appointment updates.
--
-- Written to be safe on both a database built from these migrations and one
-- that was changed by hand in the dashboard.
--
-- AFTER APPLYING: register the salon owner as admin, otherwise nobody can
-- open the admin panel:
--   INSERT INTO public.admin_users (user_id)
--   SELECT id FROM auth.users WHERE email = 'owner@example.com';
-- ============================================================================


-- ─── 1. Schema drift ────────────────────────────────────────────────────────

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns
             WHERE table_schema = 'public' AND table_name = 'appointments'
               AND column_name = 'appointment_date') THEN
    ALTER TABLE public.appointments ALTER COLUMN appointment_date DROP NOT NULL;
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.columns
             WHERE table_schema = 'public' AND table_name = 'appointments'
               AND column_name = 'appointment_time') THEN
    ALTER TABLE public.appointments ALTER COLUMN appointment_time DROP NOT NULL;
  END IF;
END $$;

-- One booking per date/time contradicts a salon with 7 seats.
DROP INDEX IF EXISTS public.idx_unique_appointment_slot;

-- Returned only appointment times but was SECURITY DEFINER and unused.
DROP FUNCTION IF EXISTS public.get_booked_slots(date);

ALTER TABLE public.appointments
  ADD COLUMN IF NOT EXISTS notification_sent_at timestamptz;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.appointments
                 WHERE start_time IS NULL OR end_time IS NULL) THEN
    ALTER TABLE public.appointments
      ALTER COLUMN start_time SET NOT NULL,
      ALTER COLUMN end_time SET NOT NULL;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'appointments_end_after_start') THEN
    ALTER TABLE public.appointments
      ADD CONSTRAINT appointments_end_after_start
      CHECK (end_time > start_time) NOT VALID;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_appointments_end_time ON public.appointments (end_time);


-- ─── 2. Admins ──────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.admin_users (
  user_id uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

-- Managed only from the SQL editor / service role. Admins may see their own row.
DROP POLICY IF EXISTS "Admins can read own row" ON public.admin_users;
CREATE POLICY "Admins can read own row"
ON public.admin_users
FOR SELECT
TO authenticated
USING (user_id = auth.uid());

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (SELECT 1 FROM public.admin_users WHERE user_id = auth.uid());
$$;


-- ─── 3. RLS ─────────────────────────────────────────────────────────────────

-- appointments: no public access at all; bookings go through create_appointment().
DROP POLICY IF EXISTS "Anyone can create appointments" ON public.appointments;
DROP POLICY IF EXISTS "Public can check availability" ON public.appointments;
DROP POLICY IF EXISTS "Authenticated users can view all appointments" ON public.appointments;
DROP POLICY IF EXISTS "Authenticated users can update appointments" ON public.appointments;
DROP POLICY IF EXISTS "Authenticated users can delete appointments" ON public.appointments;
DROP POLICY IF EXISTS "Admins can view appointments" ON public.appointments;
DROP POLICY IF EXISTS "Admins can update appointments" ON public.appointments;
DROP POLICY IF EXISTS "Admins can delete appointments" ON public.appointments;

CREATE POLICY "Admins can view appointments"
ON public.appointments FOR SELECT TO authenticated
USING (public.is_admin());

CREATE POLICY "Admins can update appointments"
ON public.appointments FOR UPDATE TO authenticated
USING (public.is_admin())
WITH CHECK (public.is_admin());

CREATE POLICY "Admins can delete appointments"
ON public.appointments FOR DELETE TO authenticated
USING (public.is_admin());

-- salon_holidays: public read (the booking calendar greys out closed days), admin write.
DROP POLICY IF EXISTS "Admins can manage holidays" ON public.salon_holidays;
DROP POLICY IF EXISTS "Admins can insert holidays" ON public.salon_holidays;
DROP POLICY IF EXISTS "Admins can update holidays" ON public.salon_holidays;
DROP POLICY IF EXISTS "Admins can delete holidays" ON public.salon_holidays;

CREATE POLICY "Admins can insert holidays"
ON public.salon_holidays FOR INSERT TO authenticated
WITH CHECK (public.is_admin());

CREATE POLICY "Admins can update holidays"
ON public.salon_holidays FOR UPDATE TO authenticated
USING (public.is_admin())
WITH CHECK (public.is_admin());

CREATE POLICY "Admins can delete holidays"
ON public.salon_holidays FOR DELETE TO authenticated
USING (public.is_admin());

-- salon_settings had no RLS at all, so anyone could rewrite the capacity.
ALTER TABLE public.salon_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can view settings" ON public.salon_settings;
DROP POLICY IF EXISTS "Admins can update settings" ON public.salon_settings;

CREATE POLICY "Admins can view settings"
ON public.salon_settings FOR SELECT TO authenticated
USING (public.is_admin());

CREATE POLICY "Admins can update settings"
ON public.salon_settings FOR UPDATE TO authenticated
USING (public.is_admin())
WITH CHECK (public.is_admin());

ALTER TABLE public.salon_settings
  DROP CONSTRAINT IF EXISTS salon_settings_capacity_check;
ALTER TABLE public.salon_settings
  ADD CONSTRAINT salon_settings_capacity_check
  CHECK (total_capacity >= 0 AND max_online_per_slot >= 0 AND max_online_per_slot <= total_capacity);


-- ─── 4. Booking functions ───────────────────────────────────────────────────

-- The 2-argument version is replaced by one with an optional exclusion; both
-- existing would make PostgREST calls ambiguous.
DROP FUNCTION IF EXISTS public.check_slot_availability(timestamptz, timestamptz);

CREATE OR REPLACE FUNCTION public.check_slot_availability(
  check_start timestamptz,
  check_end timestamptz,
  p_exclude_id uuid DEFAULT NULL
) RETURNS json
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  settings public.salon_settings%ROWTYPE;
  v_max_online integer;
  v_online_count integer;
  v_total_count integer;
  v_state text;
BEGIN
  -- Holidays are calendar days in the salon's own timezone, not UTC.
  IF EXISTS (
    SELECT 1 FROM public.salon_holidays
    WHERE holiday_date = (check_start AT TIME ZONE 'Europe/Belgrade')::date
  ) THEN
    RETURN json_build_object(
      'state', 'FULL',
      'online_count', 0,
      'total_count', 0,
      'max_online', 0,
      'total_capacity', 0,
      'holiday', true
    );
  END IF;

  SELECT * INTO settings FROM public.salon_settings WHERE id = 1;

  -- online_ratio caps online bookings in addition to the hard per-slot limit.
  v_max_online := LEAST(
    settings.max_online_per_slot,
    floor(settings.total_capacity * settings.online_ratio)::integer
  );

  SELECT
    COUNT(*) FILTER (WHERE source = 'online'),
    COUNT(*)
  INTO v_online_count, v_total_count
  FROM public.appointments
  WHERE status <> 'cancelled'
    AND id IS DISTINCT FROM p_exclude_id
    AND start_time < check_end
    AND end_time > check_start;

  IF v_total_count >= settings.total_capacity THEN
    v_state := 'FULL';
  ELSIF v_online_count >= v_max_online THEN
    v_state := 'ONLINE_FULL_WALKIN_AVAILABLE';
  ELSE
    v_state := 'ONLINE_AVAILABLE';
  END IF;

  RETURN json_build_object(
    'state', v_state,
    'online_count', v_online_count,
    'total_count', v_total_count,
    'max_online', v_max_online,
    'total_capacity', settings.total_capacity,
    'holiday', false
  );
END;
$$;

-- Availability for a whole day in one round trip (instead of one RPC per slot).
CREATE OR REPLACE FUNCTION public.get_slots_availability(
  p_starts timestamptz[],
  p_duration_minutes integer DEFAULT 60,
  p_exclude_id uuid DEFAULT NULL
) RETURNS json
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_result json;
BEGIN
  IF p_starts IS NULL OR cardinality(p_starts) = 0 THEN
    RETURN '[]'::json;
  END IF;
  IF cardinality(p_starts) > 48 THEN
    RAISE EXCEPTION 'Too many slots requested';
  END IF;
  IF p_duration_minutes IS NULL OR p_duration_minutes < 15 OR p_duration_minutes > 480 THEN
    RAISE EXCEPTION 'Invalid duration';
  END IF;

  SELECT json_agg(
    json_build_object(
      'start', s,
      'availability', public.check_slot_availability(
        s, s + make_interval(mins => p_duration_minutes), p_exclude_id
      )
    )
    ORDER BY s
  )
  INTO v_result
  FROM unnest(p_starts) AS s;

  RETURN v_result;
END;
$$;

-- Shared input validation. Returns an error message or NULL.
CREATE OR REPLACE FUNCTION public.validate_appointment_input(
  p_customer_name text,
  p_customer_phone text,
  p_customer_email text,
  p_service_type text,
  p_notes text,
  p_require_phone boolean
) RETURNS text
LANGUAGE plpgsql
IMMUTABLE
SET search_path = public
AS $$
BEGIN
  IF p_customer_name IS NULL OR char_length(btrim(p_customer_name)) NOT BETWEEN 2 AND 100 THEN
    RETURN 'Ime mora imati između 2 i 100 karaktera.';
  END IF;

  IF p_require_phone THEN
    IF p_customer_phone IS NULL
       OR p_customer_phone !~ '^\+?[0-9 ()/.-]{6,25}$'
       OR char_length(regexp_replace(p_customer_phone, '\D', '', 'g')) NOT BETWEEN 6 AND 15 THEN
      RETURN 'Unesite ispravan broj telefona.';
    END IF;
  ELSIF p_customer_phone IS NOT NULL AND char_length(p_customer_phone) > 30 THEN
    RETURN 'Broj telefona je predugačak.';
  END IF;

  IF p_customer_email IS NOT NULL AND (
       char_length(p_customer_email) > 254
       OR p_customer_email !~ '^[^@\s<>"]+@[^@\s<>"]+\.[^@\s<>"]+$'
     ) THEN
    RETURN 'Unesite ispravnu email adresu.';
  END IF;

  IF p_service_type IS NULL OR char_length(btrim(p_service_type)) NOT BETWEEN 1 AND 100 THEN
    RETURN 'Izaberite uslugu.';
  END IF;

  IF p_notes IS NOT NULL AND char_length(p_notes) > 500 THEN
    RETURN 'Napomena može imati najviše 500 karaktera.';
  END IF;

  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_appointment(
  p_customer_name text,
  p_customer_phone text,
  p_customer_email text,
  p_start_time timestamptz,
  p_end_time timestamptz,
  p_service_type text,
  p_notes text DEFAULT NULL,
  p_source text DEFAULT 'online'
) RETURNS json
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_is_admin boolean := public.is_admin();
  v_source text := coalesce(p_source, 'online');
  v_name text := btrim(p_customer_name);
  v_phone text := nullif(btrim(p_customer_phone), '');
  v_email text := nullif(lower(btrim(p_customer_email)), '');
  v_service text := btrim(p_service_type);
  v_notes text := nullif(btrim(p_notes), '');
  v_local_start timestamp;
  v_error text;
  v_status json;
  v_id uuid;
BEGIN
  IF v_source NOT IN ('online', 'walkin') THEN
    RETURN json_build_object('success', false, 'error', 'Neispravan izvor termina.');
  END IF;

  -- Only the salon may enter walk-ins; otherwise anyone could bypass the online quota.
  IF v_source = 'walkin' AND NOT v_is_admin THEN
    RETURN json_build_object('success', false, 'error', 'Nemate dozvolu za ovu akciju.');
  END IF;

  v_error := public.validate_appointment_input(
    v_name, v_phone, v_email, v_service, v_notes, NOT v_is_admin
  );
  IF v_error IS NOT NULL THEN
    RETURN json_build_object('success', false, 'error', v_error);
  END IF;

  IF p_start_time IS NULL OR p_end_time IS NULL
     OR p_end_time <= p_start_time
     OR p_end_time - p_start_time > interval '8 hours' THEN
    RETURN json_build_object('success', false, 'error', 'Neispravno vreme termina.');
  END IF;

  IF NOT v_is_admin THEN
    v_local_start := p_start_time AT TIME ZONE 'Europe/Belgrade';

    IF p_start_time <= now() THEN
      RETURN json_build_object('success', false, 'error', 'Izabrani termin je već prošao.');
    END IF;
    IF p_start_time > now() + interval '61 days' THEN
      RETURN json_build_object('success', false, 'error', 'Termin se može zakazati najviše 60 dana unapred.');
    END IF;
    IF extract(isodow FROM v_local_start) = 7 THEN
      RETURN json_build_object('success', false, 'error', 'Nedeljom ne radimo.');
    END IF;
  END IF;

  -- Serialise bookings so two simultaneous requests cannot both take the last seat.
  PERFORM pg_advisory_xact_lock(hashtext('public.appointments.capacity'));

  IF NOT v_is_admin THEN
    -- Abuse limits: per phone number, and overall burst protection.
    IF (SELECT count(*) FROM public.appointments
        WHERE source = 'online'
          AND status <> 'cancelled'
          AND end_time > now()
          AND regexp_replace(customer_phone, '\D', '', 'g') = regexp_replace(v_phone, '\D', '', 'g')
       ) >= 3 THEN
      RETURN json_build_object('success', false, 'error',
        'Sa ovim brojem telefona već imate 3 zakazana termina. Za više termina pozovite salon.');
    END IF;

    IF (SELECT count(*) FROM public.appointments
        WHERE source = 'online' AND created_at > now() - interval '10 minutes') >= 20 THEN
      RETURN json_build_object('success', false, 'error',
        'Trenutno je previše zahteva. Pokušajte ponovo za nekoliko minuta ili nas pozovite.');
    END IF;
  END IF;

  v_status := public.check_slot_availability(p_start_time, p_end_time);

  IF v_status->>'state' = 'FULL' THEN
    RETURN json_build_object('success', false, 'error', 'Termin je popunjen.', 'status', v_status);
  END IF;

  IF v_source = 'online' AND v_status->>'state' <> 'ONLINE_AVAILABLE' THEN
    RETURN json_build_object('success', false,
      'error', 'Online zakazivanje za ovaj termin nije dostupno, ali možete doći bez zakazivanja.',
      'status', v_status);
  END IF;

  INSERT INTO public.appointments (
    customer_name, customer_phone, customer_email, start_time, end_time,
    service_type, notes, source, status
  ) VALUES (
    v_name, coalesce(v_phone, '—'), v_email, p_start_time, p_end_time,
    v_service, v_notes, v_source, 'confirmed'
  )
  RETURNING id INTO v_id;

  RETURN json_build_object(
    'success', true,
    'appointment_id', v_id,
    'status', public.check_slot_availability(p_start_time, p_end_time)
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.update_appointment(
  p_appointment_id uuid,
  p_start_time timestamptz,
  p_end_time timestamptz,
  p_service_type text,
  p_customer_name text,
  p_customer_phone text,
  p_notes text,
  p_status text
) RETURNS json
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_current public.appointments%ROWTYPE;
  v_status json;
  v_error text;
BEGIN
  IF NOT public.is_admin() THEN
    RETURN json_build_object('success', false, 'error', 'Nemate dozvolu za ovu akciju.');
  END IF;

  IF p_status NOT IN ('pending', 'confirmed', 'cancelled') THEN
    RETURN json_build_object('success', false, 'error', 'Neispravan status.');
  END IF;

  IF p_start_time IS NULL OR p_end_time IS NULL OR p_end_time <= p_start_time THEN
    RETURN json_build_object('success', false, 'error', 'Neispravno vreme termina.');
  END IF;

  v_error := public.validate_appointment_input(
    btrim(p_customer_name), nullif(btrim(p_customer_phone), ''), NULL,
    btrim(p_service_type), nullif(btrim(p_notes), ''), false
  );
  IF v_error IS NOT NULL THEN
    RETURN json_build_object('success', false, 'error', v_error);
  END IF;

  PERFORM pg_advisory_xact_lock(hashtext('public.appointments.capacity'));

  SELECT * INTO v_current FROM public.appointments WHERE id = p_appointment_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN json_build_object('success', false, 'error', 'Termin nije pronađen.');
  END IF;

  -- Re-check capacity when the appointment moves, or when a cancelled one is re-activated.
  IF p_status <> 'cancelled' AND (
       v_current.start_time <> p_start_time
       OR v_current.end_time <> p_end_time
       OR v_current.status = 'cancelled'
     ) THEN
    v_status := public.check_slot_availability(p_start_time, p_end_time, p_appointment_id);

    IF v_status->>'state' = 'FULL'
       OR (v_current.source = 'online' AND v_status->>'state' <> 'ONLINE_AVAILABLE') THEN
      RETURN json_build_object('success', false,
        'error', 'Termin je popunjen ili nije dostupan za ovaj tip rezervacije.',
        'status', v_status);
    END IF;
  END IF;

  UPDATE public.appointments
  SET
    start_time = p_start_time,
    end_time = p_end_time,
    service_type = btrim(p_service_type),
    customer_name = btrim(p_customer_name),
    customer_phone = coalesce(nullif(btrim(p_customer_phone), ''), '—'),
    notes = nullif(btrim(p_notes), ''),
    status = p_status
  WHERE id = p_appointment_id;

  RETURN json_build_object(
    'success', true,
    'status', public.check_slot_availability(p_start_time, p_end_time)
  );
END;
$$;


-- ─── 5. Privileges ──────────────────────────────────────────────────────────
-- Postgres grants EXECUTE to PUBLIC by default; be explicit about who may call what.

REVOKE ALL ON FUNCTION public.is_admin() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.check_slot_availability(timestamptz, timestamptz, uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_slots_availability(timestamptz[], integer, uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.validate_appointment_input(text, text, text, text, text, boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.create_appointment(text, text, text, timestamptz, timestamptz, text, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.update_appointment(uuid, timestamptz, timestamptz, text, text, text, text, text) FROM PUBLIC;

REVOKE ALL ON FUNCTION public.validate_appointment_input(text, text, text, text, text, boolean) FROM anon, authenticated;
REVOKE ALL ON FUNCTION public.update_appointment(uuid, timestamptz, timestamptz, text, text, text, text, text) FROM anon;

GRANT EXECUTE ON FUNCTION public.is_admin() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.check_slot_availability(timestamptz, timestamptz, uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_slots_availability(timestamptz[], integer, uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.create_appointment(text, text, text, timestamptz, timestamptz, text, text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.update_appointment(uuid, timestamptz, timestamptz, text, text, text, text, text) TO authenticated;


-- ═══ migrations/20261001130000_capacity_per_start_time.sql ═══
-- ============================================================================
-- Count capacity per exact start time instead of per overlapping hour.
--
-- Service durations are not fixed, so the 60-minute end_time is only
-- informational. "Max 4 online bookings per slot" now means: at most 4 online
-- appointments that START at exactly that time. A full 11:00 no longer blocks
-- 11:30. The same applies to total_capacity (online + walk-in).
--
-- check_end is kept in the signature so existing callers keep working, but it
-- no longer affects the result.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.check_slot_availability(
  check_start timestamptz,
  check_end timestamptz,
  p_exclude_id uuid DEFAULT NULL
) RETURNS json
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  settings public.salon_settings%ROWTYPE;
  v_max_online integer;
  v_online_count integer;
  v_total_count integer;
  v_state text;
BEGIN
  -- Holidays are calendar days in the salon's own timezone, not UTC.
  IF EXISTS (
    SELECT 1 FROM public.salon_holidays
    WHERE holiday_date = (check_start AT TIME ZONE 'Europe/Belgrade')::date
  ) THEN
    RETURN json_build_object(
      'state', 'FULL',
      'online_count', 0,
      'total_count', 0,
      'max_online', 0,
      'total_capacity', 0,
      'holiday', true
    );
  END IF;

  SELECT * INTO settings FROM public.salon_settings WHERE id = 1;

  -- online_ratio caps online bookings in addition to the hard per-slot limit.
  v_max_online := LEAST(
    settings.max_online_per_slot,
    floor(settings.total_capacity * settings.online_ratio)::integer
  );

  -- Only appointments that start at exactly this time count against the slot.
  SELECT
    COUNT(*) FILTER (WHERE source = 'online'),
    COUNT(*)
  INTO v_online_count, v_total_count
  FROM public.appointments
  WHERE status <> 'cancelled'
    AND id IS DISTINCT FROM p_exclude_id
    AND start_time = check_start;

  IF v_total_count >= settings.total_capacity THEN
    v_state := 'FULL';
  ELSIF v_online_count >= v_max_online THEN
    v_state := 'ONLINE_FULL_WALKIN_AVAILABLE';
  ELSE
    v_state := 'ONLINE_AVAILABLE';
  END IF;

  RETURN json_build_object(
    'state', v_state,
    'online_count', v_online_count,
    'total_count', v_total_count,
    'max_online', v_max_online,
    'total_capacity', settings.total_capacity,
    'holiday', false
  );
END;
$$;

REVOKE ALL ON FUNCTION public.check_slot_availability(timestamptz, timestamptz, uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.check_slot_availability(timestamptz, timestamptz, uuid) TO anon, authenticated;


-- ═══ migrations/20261002090000_enable_realtime.sql ═══
-- The admin dashboard listens for appointment changes (live refresh).
-- On Supabase this needs the table in the supabase_realtime publication.
-- Guarded so it is a no-op where the publication does not exist or already
-- contains the table.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime')
     AND NOT EXISTS (
       SELECT 1 FROM pg_publication_tables
       WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'appointments'
     ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.appointments;
  END IF;
END $$;


COMMIT;
